export {default as Onboarding} from './Onboarding'
export {default as Welcome} from './Welcome'
export {default as Account} from './Onboarding'
export {default as Details} from './Onboarding'
export {default as Home} from './Home'